
# Part 1 — NumPy, introduced clearly

Before NumPy, think about a regular Python list.
A list is flexible. It can hold many kinds of values, and it is great for general programming.

But when we want to do **numerical computing**, lists are clunky:
- math on every item takes more code
- lists are not designed for fast large-scale numerical operations

NumPy gives us a better tool for numbers:
- a **NumPy array** stores numerical data efficiently
- it lets us do math on an entire collection at once

In [1]:

import numpy as np

scores_list = [72, 88, 91, 84, 95]

print("Python list:")
print(scores_list)
print("Type:", type(scores_list))

Python list:
[72, 88, 91, 84, 95]
Type: <class 'list'>

In [2]:

# A list does not automatically do element-by-element math
# This repeats the list rather than doubling each value
print(scores_list * 2)

[72, 88, 91, 84, 95, 72, 88, 91, 84, 95]

In [3]:

scores = np.array(scores_list)

print("NumPy array:")
print(scores)
print("Type:", type(scores))
print("Shape:", scores.shape)

NumPy array:
[72 88 91 84 95]
Type: <class 'numpy.ndarray'>
Shape: (5,)

In [4]:

# NumPy does element-by-element math
print("scores + 5:", scores + 5)
print("scores * 2:", scores * 2)
print("Average:", np.mean(scores))
print("Highest score:", np.max(scores))

scores + 5: [ 77  93  96  89 100]
scores * 2: [144 176 182 168 190]
Average: 86.0
Highest score: 95


## Why this matters

With NumPy, we can think in terms of:
- "add 5 to every score"
- "double every value"
- "find the average"

instead of writing loops for every small task.

That is why NumPy is the foundation for a lot of scientific and data-analysis work in Python.


## Example: city coordinates

Suppose each city has:
- a latitude
- a longitude

We can store all coordinates in a 2D NumPy array and compute distances from a reference point.

In [5]:

city_names = np.array(["Memphis", "Nashville", "St. Louis", "Dallas", "Chicago", "Atlanta"])

# Each row is [latitude, longitude]
city_coords = np.array([
    [35.1495, -90.0490],
    [36.1627, -86.7816],
    [38.6270, -90.1994],
    [32.7767, -96.7970],
    [41.8781, -87.6298],
    [33.7490, -84.3880]
])

center = np.array([39.8283, -98.5795])

print("City coordinates array:")
print(city_coords)
print("Shape:", city_coords.shape)

City coordinates array:
[[ 35.1495 -90.049 ]
 [ 36.1627 -86.7816]
 [ 38.627  -90.1994]
 [ 32.7767 -96.797 ]
 [ 41.8781 -87.6298]
 [ 33.749  -84.388 ]]
Shape: (6, 2)

In [6]:

# Compute Euclidean distance from each city to the reference point
distances = np.sqrt(np.sum((city_coords - center) ** 2, axis=1))

print("Distances from the reference point:")
for i in range(len(city_names)):
    print(city_names[i], "->", round(distances[i], 2))

Distances from the reference point:
Memphis -> 9.73
Nashville -> 12.35
St. Louis -> 8.47
Dallas -> 7.27
Chicago -> 11.14
Atlanta -> 15.44

In [7]:

# Find the city closest to the reference point
closest_index = np.argmin(distances)
print("Closest city:", city_names[closest_index])

Closest city: Dallas


# Part 2 — Transition to pandas

NumPy is excellent for numerical arrays.

But in data analytics, we usually want to work with:
- column names
- CSV files
- mixed data types
- filtering rows
- grouped summaries

That is what pandas is for.

In [8]:

import pandas as pd


# Part 3 —

In [9]:

al = pd.read_csv("Top 10 Albums By Year.csv")
al.head()

,Ranking,Album,Artist,Year,Tracks,Length (mins),Worldwide Sales
0,1,Thriller,Michael Jackson,1982,9,42,70000000
1,2,Back in Black,AC/DC,1980,10,42,50000000
2,3,The Bodyguard,Whitney Houston,1992,12,57,45000000
3,4,Rumours,Fleetwood Mac,1977,11,39,40000000
4,5,Saturday Night Fever,Bee Gees,1977,17,76,40000000

In [10]:

al.shape
  #shape gives you the number of rows and columns, respectively.

print('Number of rows', al.shape[0])
print('Number of columns', al.shape[1])

Number of rows 25
Number of columns 7

In [11]:

al.columns
print("5th column:", al.columns[5])

5th column: Length (mins)

In [12]:

al.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ranking          25 non-null     int64
 1   Album            25 non-null     object
 2   Artist           25 non-null     object
 3   Year             25 non-null     int64
 4   Tracks           25 non-null     int64
 5   Length (mins)    25 non-null     int64
 6   Worldwide Sales  25 non-null     object
dtypes: int64(4), object(3)
memory usage: 1.5+ KB

In [13]:

al.describe()

         Ranking         Year     Tracks  Length (mins)
count  25.000000    25.000000  25.000000      25.000000
mean   13.000000  1997.880000  13.040000      52.680000
std     7.359801    14.723337   2.715388      13.539202
min     1.000000  1969.000000   9.000000      34.000000
25%     7.000000  1991.000000  11.000000      42.000000
50%    13.000000  1997.000000  12.000000      48.000000
75%    19.000000  2011.000000  14.000000      61.000000
max    25.000000  2021.000000  20.000000      77.000000


## A few questions about the data

1. What proportion of albums have 15 or fewer tracks?
2. What is the mean album length in minutes?

In [14]:

#al[al.columns[4]]    #another way to get tracks

#al['Tracks'] < 15   #boolean comparison. You can use a Boolean result to extract data.

#pt1 proportion
#al['Tracks'][al['Tracks'] < 15].shape[0]/al['Tracks'].shape[0]

#pt2 mean 
# sum(al['Length (mins)'])/al.shape[0]

(al["Tracks"] <= 15).mean()

#print(al['Artist'])

#print(al.Artist[0])

#print(al['Ranking']<=5)
#print(al['Ranking'], al['Ranking']<=5)
#print(al['Album'], al['Ranking']<=5)

np.float64(0.76)

In [15]:

al["Length (mins)"].mean()
al["Length (mins)"].max()
al["Length (mins)"].min()
al["Length (mins)"].count()

np.int64(25)


## Checking data types

Notice that `Worldwide Sales` is not numeric yet.
That means pandas will not include it properly in numeric summary statistics.

Let's fix it.

In [16]:

al.dtypes

Ranking             int64
Album              object
Artist             object
Year                int64
Tracks              int64
Length (mins)       int64
Worldwide Sales    object
dtype: object

In [17]:

al["Worldwide Sales"] = pd.to_numeric(al["Worldwide Sales"], errors="coerce")
al.dtypes

Ranking              int64
Album               object
Artist              object
Year                 int64
Tracks               int64
Length (mins)        int64
Worldwide Sales    float64
dtype: object

In [18]:

al.describe()

         Ranking         Year     Tracks  Length (mins)  Worldwide Sales
count  25.000000    25.000000  25.000000      25.000000     2.400000e+01
mean   13.000000  1997.880000  13.040000      52.680000     2.821250e+07
std     7.359801    14.723337   2.715388      13.539202     1.553107e+07
min     1.000000  1969.000000   9.000000      34.000000     2.500000e+06
25%     7.000000  1991.000000  11.000000      42.000000     1.900000e+07
50%    13.000000  1997.000000  12.000000      48.000000     3.050000e+07
75%    19.000000  2011.000000  14.000000      61.000000     3.475000e+07
max    25.000000  2021.000000  20.000000      77.000000     7.000000e+07


## Creating a new column

Assume the worldwide sales are as of 2022.
Create a column showing the average sales per year since release.

In [19]:

al["Sales per Year"] = al["Worldwide Sales"] / (2022 - al["Year"] + 1)
al[["Album", "Artist", "Year", "Worldwide Sales", "Sales per Year"]].head()

,Album,Artist,Year,Worldwide Sales,Sales per Year
0,Thriller,Michael Jackson,1982,70000000.0,1.707317e+06
1,Back in Black,AC/DC,1980,50000000.0,1.162791e+06
2,The Bodyguard,Whitney Houston,1992,45000000.0,1.451613e+06
3,Rumours,Fleetwood Mac,1977,40000000.0,8.695652e+05
4,Saturday Night Fever,Bee Gees,1977,40000000.0,8.695652e+05


## Finding the highest-selling album

In [20]:

al["Worldwide Sales"].argmax()

#argmax gives you the index of the max

np.int64(0)

In [21]:
#iloc lets you select that particular row (highest index)

highest_index = al["Worldwide Sales"].argmax()
highest_album = al.iloc[highest_index]
print(highest_album["Album"], "-", highest_album["Artist"])

#lowest selling
lowest_index = al["Worldwide Sales"].argmin()
lowest_album = al.iloc[lowest_index]
print(lowest_album["Album"], "-", lowest_album["Artist"])

#al["Worldwide Sales"].argmin()
#print(al.iloc[al["Worldwide Sales"].argmin()])

Thriller - Michael Jackson
Lemonade - Beyonce


## Filtering examples from your earlier notebook

In [22]:

# Albums ranked 1 through 20
top20 = al[al["Ranking"] <= 20]      #not intuitive
top20.shape

#top 20 has the whole data set

(20, 8)

In [23]:

# Albums with sales greater than 20 million
more_than_20m = al[al["Worldwide Sales"] > 20000000]
more_than_20m[["Album", "Artist", "Worldwide Sales"]]

                   Album             Artist  Worldwide Sales
0               Thriller    Michael Jackson       70000000.0
1          Back in Black              AC/DC       50000000.0
2          The Bodyguard    Whitney Houston       45000000.0
3                Rumours      Fleetwood Mac       40000000.0
4   Saturday Night Fever           Bee Gees       40000000.0
5           Come On Over       Shania Twain       40000000.0
6     Jagged Little Pill  Alanis Morissette       33000000.0
7                     21              Adele       31000000.0
8             Abbey Road        The Beatles       31000000.0
9              Metallica          Metallica       31000000.0
10    Born in the U.S.A.  Bruce Springsteen       30000000.0
11      Falling into You        Celine Dion       32000000.0
14                    25              Adele       22000000.0
16             Dangerous    Michael Jackson       32000000.0
17         Hybrid Theory        Linkin Park       27000000.0
18   No Strings Attached              NSYNC       24000000.0
24       The Eminem Show             Eminem       27000000.0

In [24]:

# Albums from 1997
al[al["Year"] == 1997][["Year", "Artist", "Album"]]

   Year        Artist         Album
5  1997  Shania Twain  Come On Over


# Part 4 — A second CSV for more pandas practice

Now let's use `Movie-Data.csv` to practice the most important pandas skills:
- selecting columns
- filtering rows
- sorting
- creating a new column
- grouping

In [25]:

movies = pd.read_csv("Movie-Data.csv")
#movies.head()
#movies.info()
#movies.dtypes
movies.describe()

              Year     Runtime   Rating  Revenue_Millions  Votes_Thousands
count    12.000000   12.000000  12.0000         12.000000        12.000000
mean   2015.666667  127.750000   7.8750        706.066667       847.916667
std       4.478907   22.974789   0.6107        381.488256       647.581018
min    2006.000000   95.000000   6.9000        236.000000       245.000000
25%    2014.750000  108.000000   7.4500        435.075000       495.000000
50%    2016.000000  127.500000   8.0000        653.850000       680.000000
75%    2017.250000  145.000000   8.1750        842.300000       840.000000
max    2023.000000  169.000000   8.8000       1445.600000      2400.000000

In [26]:

#movies[["Title", "Genre", "Rating"]].head()

movies[["Title", "Genre", "Rating"]].iloc[0]

Title     La La Land
Genre        Musical
Rating           8.0
Name: 0, dtype: object

In [27]:

movies[movies["Rating"] > 8.0]

,Title,Genre,Year,Runtime,Rating,Revenue_Millions,Votes_Thousands,Director
4,Inception,Sci-Fi,2010,148,8.8,836.8,2400,Christopher Nolan
5,Coco,Animation,2017,105,8.4,807.1,580,Lee Unkrich
8,Interstellar,Sci-Fi,2014,169,8.7,677.5,1900,Christopher Nolan
9,Inside Out,Animation,2015,95,8.1,858.8,720,Pete Docter

In [28]:

movies[(movies["Genre"] == "Sci-Fi") & (movies["Rating"] >= 8.0)]

,Title,Genre,Year,Runtime,Rating,Revenue_Millions,Votes_Thousands,Director
4,Inception,Sci-Fi,2010,148,8.8,836.8,2400,Christopher Nolan
6,The Martian,Sci-Fi,2015,144,8.0,630.2,900,Ridley Scott
7,Dune,Sci-Fi,2021,155,8.0,402.0,710,Denis Villeneuve
8,Interstellar,Sci-Fi,2014,169,8.7,677.5,1900,Christopher Nolan

In [29]:

movies.sort_values("Revenue_Millions", ascending=False).head(5)

,Title,Genre,Year,Runtime,Rating,Revenue_Millions,Votes_Thousands,Director
3,Barbie,Comedy,2023,114,7.0,1445.6,510,Greta Gerwig
2,Black Panther,Action,2018,134,7.3,1347.0,820,Ryan Coogler
9,Inside Out,Animation,2015,95,8.1,858.8,720,Pete Docter
4,Inception,Sci-Fi,2010,148,8.8,836.8,2400,Christopher Nolan
5,Coco,Animation,2017,105,8.4,807.1,580,Lee Unkrich

In [30]:

movies["Revenue_per_Minute"] = movies["Revenue_Millions"] / movies["Runtime"]
movies[["Title", "Revenue_Millions", "Runtime", "Revenue_per_Minute"]].head()

            Title  Revenue_Millions  Runtime  Revenue_per_Minute
0      La La Land             446.1      128            3.485156
1  Hidden Figures             236.0      127            1.858268
2   Black Panther            1347.0      134           10.052239
3          Barbie            1445.6      114           12.680702
4       Inception             836.8      148            5.654054

In [31]:

movies.groupby("Genre")["Rating"].mean().sort_values(ascending=False)

Genre
Sci-Fi       8.375
Animation    8.250
Drama        7.800
Musical      7.750
Action       7.300
Comedy       6.950
Name: Rating, dtype: float64


# Hands-on Activity

Use the **albums CSV** first, then the **movie CSV**.

Try these on your own before checking answers.


## Activity A — Albums CSV

1. Print the first 5 rows.
2. How many rows and columns are there?
3. Print the column names.
4. Show only the `Album` and `Artist` columns.
5. Filter to albums released after 2010.
6. Filter to albums with more than 15 tracks.
7. Sort by `Length (mins)` from largest to smallest.
8. Find the average `Length (mins)`.
9. Find the average `Worldwide Sales` after converting the column to numeric.
10. Which artist appears more than once in this file?

In [32]:
# Write your answer here
al.head()

,Ranking,Album,Artist,Year,Tracks,Length (mins),Worldwide Sales,Sales per Year
0,1,Thriller,Michael Jackson,1982,9,42,70000000.0,1.707317e+06
1,2,Back in Black,AC/DC,1980,10,42,50000000.0,1.162791e+06
2,3,The Bodyguard,Whitney Houston,1992,12,57,45000000.0,1.451613e+06
3,4,Rumours,Fleetwood Mac,1977,11,39,40000000.0,8.695652e+05
4,5,Saturday Night Fever,Bee Gees,1977,17,76,40000000.0,8.695652e+05

In [33]:
# Write your answer here
al.shape

rows=al.shape[0]
cols=al.shape[1]
print('rows',rows)
print('cols',cols)

rows 25
cols 8

In [44]:
# Write your answer here
#a = al.columns
#print(a)

al[["Ranking", "Album", "Year", "Tracks", "Length (mins)", "Worldwide Sales", "Sales per Year"]]

,Ranking,Album,Year,Tracks,Length (mins),Worldwide Sales,Sales per Year
0,1,Thriller,1982,9,42,70000000.0,1.707317e+06
1,2,Back in Black,1980,10,42,50000000.0,1.162791e+06
2,3,The Bodyguard,1992,12,57,45000000.0,1.451613e+06
3,4,Rumours,1977,11,39,40000000.0,8.695652e+05
4,5,Saturday Night Fever,1977,17,76,40000000.0,8.695652e+05
5,6,Come On Over,1997,16,60,40000000.0,1.538462e+06
6,7,Jagged Little Pill,1995,13,57,33000000.0,1.178571e+06
7,8,21,2011,11,49,31000000.0,2.583333e+06
8,9,Abbey Road,1969,17,47,31000000.0,5.740741e+05
9,10,Metallica,1991,12,63,31000000.0,9.687500e+05
10,11,Born in the U.S.A.,1984,12,47,30000000.0,7.692308e+05
11,12,Falling into You,1996,16,76,32000000.0,1.185185e+06
12,13,Sour,2021,11,34,5600000.0,2.800000e+06
13,14,1989,2014,13,49,14000000.0,1.555556e+06
14,15,25,2015,11,48,22000000.0,2.750000e+06
15,16,Future Nostalgia,2020,11,37,7000000.0,2.333333e+06
16,17,Dangerous,1991,14,77,32000000.0,1.000000e+06
17,18,Hybrid Theory,2000,12,38,27000000.0,1.173913e+06
18,19,No Strings Attached,2000,12,47,24000000.0,1.043478e+06
19,20,Spice,1996,10,40,NaN,NaN
20,21,Ray of Light,1998,13,66,16000000.0,6.400000e+05
21,22,Confessions,2004,17,61,20000000.0,1.052632e+06
22,23,Lemonade,2016,12,45,2500000.0,3.571429e+05
23,24,"When We All Fall Asleep, Where Do We Go?",2019,14,43,7000000.0,1.750000e+06
24,25,The Eminem Show,2002,20,77,27000000.0,1.285714e+06

In [45]:
# Write your answer here
al[["Artist", "Album"]]

               Artist                                     Album
0     Michael Jackson                                  Thriller
1               AC/DC                             Back in Black
2     Whitney Houston                             The Bodyguard
3       Fleetwood Mac                                   Rumours
4            Bee Gees                      Saturday Night Fever
5        Shania Twain                              Come On Over
6   Alanis Morissette                        Jagged Little Pill
7               Adele                                        21
8         The Beatles                                Abbey Road
9           Metallica                                 Metallica
10  Bruce Springsteen                        Born in the U.S.A.
11        Celine Dion                          Falling into You
12     Olivia Rodrigo                                      Sour
13       Taylor Swift                                      1989
14              Adele                                        25
15           Dua Lipa                          Future Nostalgia
16    Michael Jackson                                 Dangerous
17        Linkin Park                             Hybrid Theory
18              NSYNC                       No Strings Attached
19        Spice Girls                                     Spice
20            Madonna                              Ray of Light
21              Usher                               Confessions
22            Beyonce                                  Lemonade
23      Billie Eilish  When We All Fall Asleep, Where Do We Go?
24             Eminem                           The Eminem Show

In [46]:
# Write your answer here
al[al['Year']>2010]

,Ranking,Album,Artist,Year,Tracks,Length (mins),Worldwide Sales,Sales per Year
7,8,21,Adele,2011,11,49,31000000.0,2.583333e+06
12,13,Sour,Olivia Rodrigo,2021,11,34,5600000.0,2.800000e+06
13,14,1989,Taylor Swift,2014,13,49,14000000.0,1.555556e+06
14,15,25,Adele,2015,11,48,22000000.0,2.750000e+06
15,16,Future Nostalgia,Dua Lipa,2020,11,37,7000000.0,2.333333e+06
22,23,Lemonade,Beyonce,2016,12,45,2500000.0,3.571429e+05
23,24,"When We All Fall Asleep, Where Do We Go?",Billie Eilish,2019,14,43,7000000.0,1.750000e+06

In [47]:
# Write your answer here
al[al["Tracks"]>15]

,Ranking,Album,Artist,Year,Tracks,Length (mins),Worldwide Sales,Sales per Year
4,5,Saturday Night Fever,Bee Gees,1977,17,76,40000000.0,8.695652e+05
5,6,Come On Over,Shania Twain,1997,16,60,40000000.0,1.538462e+06
8,9,Abbey Road,The Beatles,1969,17,47,31000000.0,5.740741e+05
11,12,Falling into You,Celine Dion,1996,16,76,32000000.0,1.185185e+06
21,22,Confessions,Usher,2004,17,61,20000000.0,1.052632e+06
24,25,The Eminem Show,Eminem,2002,20,77,27000000.0,1.285714e+06

In [48]:
# Write your answer here
al.sort_values("Length (mins)", ascending=False)

,Ranking,Album,Artist,Year,Tracks,Length (mins),Worldwide Sales,Sales per Year
24,25,The Eminem Show,Eminem,2002,20,77,27000000.0,1.285714e+06
16,17,Dangerous,Michael Jackson,1991,14,77,32000000.0,1.000000e+06
4,5,Saturday Night Fever,Bee Gees,1977,17,76,40000000.0,8.695652e+05
11,12,Falling into You,Celine Dion,1996,16,76,32000000.0,1.185185e+06
20,21,Ray of Light,Madonna,1998,13,66,16000000.0,6.400000e+05
9,10,Metallica,Metallica,1991,12,63,31000000.0,9.687500e+05
21,22,Confessions,Usher,2004,17,61,20000000.0,1.052632e+06
5,6,Come On Over,Shania Twain,1997,16,60,40000000.0,1.538462e+06
6,7,Jagged Little Pill,Alanis Morissette,1995,13,57,33000000.0,1.178571e+06
2,3,The Bodyguard,Whitney Houston,1992,12,57,45000000.0,1.451613e+06
7,8,21,Adele,2011,11,49,31000000.0,2.583333e+06
13,14,1989,Taylor Swift,2014,13,49,14000000.0,1.555556e+06
14,15,25,Adele,2015,11,48,22000000.0,2.750000e+06
8,9,Abbey Road,The Beatles,1969,17,47,31000000.0,5.740741e+05
18,19,No Strings Attached,NSYNC,2000,12,47,24000000.0,1.043478e+06
10,11,Born in the U.S.A.,Bruce Springsteen,1984,12,47,30000000.0,7.692308e+05
22,23,Lemonade,Beyonce,2016,12,45,2500000.0,3.571429e+05
23,24,"When We All Fall Asleep, Where Do We Go?",Billie Eilish,2019,14,43,7000000.0,1.750000e+06
0,1,Thriller,Michael Jackson,1982,9,42,70000000.0,1.707317e+06
1,2,Back in Black,AC/DC,1980,10,42,50000000.0,1.162791e+06
19,20,Spice,Spice Girls,1996,10,40,NaN,NaN
3,4,Rumours,Fleetwood Mac,1977,11,39,40000000.0,8.695652e+05
17,18,Hybrid Theory,Linkin Park,2000,12,38,27000000.0,1.173913e+06
15,16,Future Nostalgia,Dua Lipa,2020,11,37,7000000.0,2.333333e+06
12,13,Sour,Olivia Rodrigo,2021,11,34,5600000.0,2.800000e+06

In [49]:
# Write your answer here
al["Length (mins)"].mean()

np.float64(52.68)

In [54]:
# Write your answer here
pd.to_numeric(al["Worldwide Sales"], errors="coerce")

al.dtypes

al["Worldwide Sales"].mean()

np.float64(28212500.0)

In [77]:
# Write your answer here

bool_mask = al["Artist"].value_counts() > 1

duplicates=(bool_mask[bool_mask]).index

print(duplicates)
type(duplicates)

Index(['Michael Jackson', 'Adele'], dtype='object', name='Artist')

pandas.core.indexes.base.Index


## Activity B — Movie CSV

1. Show only the `Title`, `Genre`, and `Director` columns.
2. Filter to movies released in 2015 or later.
3. Filter to movies with rating at least 8.0.
4. Sort by `Votes_Thousands` from highest to lowest.
5. Create a new column called `Years_Old` using `2026 - Year`.
6. Which genre has the highest average rating?

In [42]:
# Write your answer here

In [43]:
# Write your answer here

In [ ]:
# Write your answer here

In [ ]:
# Write your answer here

In [ ]:
# Write your answer here

In [ ]:
# Write your answer here