## Midterm 3 DATA 242 Study Guide Notebook (Lectures 17–23)
Here is what this covers:
- a short topics list and important reminders
- practice questions
- two harder programming problems
- **one runnable answer key cell at the end**

## Topics List / High Points

### Data structures
- Lists: ordered, duplicates allowed, linear search
- Dictionaries: key-value pairs, average-case fast lookup
- Sets: unique values, fast membership checks
- Trees: hierarchical organization of data
- Heaps: priority queues, useful for top-k problems
- Graphs: shortest path, and how graphs are represented

### Big-O
- List search: `O(n)`
- List indexing: `O(1)`
- Dictionary lookup: average-case `O(1)`
- Set membership: average-case `O(1)`

### NumPy
- arrays
- vectorized operations
- broadcasting
- aggregation like `mean`, `max`, `sum`

### Pandas
- DataFrame creation
- filtering with boolean masks
- cleaning text with `.str`
- `groupby`
- creating new columns
- counting values and summarizing data

In [19]:
# Run this setup cell first.
import numpy as np
import pandas as pd
import heapq

# Main practice dataset
df = pd.DataFrame({
    "city": ["Memphis", "memphis ", "Nashville", "Memphis", "Knoxville", "Nashville", "Chattanooga", "Memphis"],
    "pollution": [55, 60, 40, 70, 30, 65, 45, 52],
    "year": [2020, 2021, 2020, 2022, 2021, 2022, 2022, 2021]
})

# Small NumPy practice array
arr = np.array([70, 72, 75, 80])

print("Data loaded.")
df

Data loaded.

          city  pollution  year
0      Memphis         55  2020
1     memphis          60  2021
2    Nashville         40  2020
3      Memphis         70  2022
4    Knoxville         30  2021
5    Nashville         65  2022
6  Chattanooga         45  2022
7      Memphis         52  2021

## Practice Questions

In [ ]:
# Practice 1
# What data structure would you use to count city frequencies and why?
# Write a short answer in a comment below, then optionally write code.

# Your answer: Dictoionary - search by key

In [ ]:
# Practice 2
# What is the time complexity of searching a list?
# Write your answer in a comment.

# Your answer: O(n)

In [3]:
# Practice 3
# How would you remove duplicates from a dataset?
# Show a Python example using a simple list of city names.

cities = ["Memphis", "Nashville", "Memphis", "Knoxville", "Nashville"]

# Your code here:
df = pd.DataFrame(cities)

#df.head()

df.drop_duplicates()

           0
0    Memphis
1  Nashville
3  Knoxville

In [7]:
# Practice 4
# Why are dictionaries fast for lookup?
# Write a short answer in a comment and create a small example dictionary.

# Your answer: Becuase of the key
city_counts = {"Memphis": 3, "Nashville": 2}

count_memphis = city_counts["Memphis"]

print(count_memphis)

3

In [8]:
# Practice 5
# Give an example where a list is better than a dictionary.
# Write a short answer in a comment, then create a simple list example.

# Your answer: When slicing or adding to the back is important.

test_scores = [91, 92, 87, 89]

test_scores.append(75)

print(test_scores)

[91, 92, 87, 89, 75]

In [9]:
# Practice 6
# What is a heap used for?
# Write your answer in a comment, then make a small min-heap from the numbers below.
# a heap is a specialized tree-based data structure used primarily for priority queues, where you need quick access to the smallest (min-heap) or largest (max-heap) element

values = [55, 30, 70, 45, 60]

# Your code here:

import heapq

heapq.heapify(values)

print(values)

[30, 45, 70, 55, 60]

In [ ]:
# Practice 7
# What is the difference between a min-heap and a max-heap?
# Write a short answer in comments.
# In a min-heap, the parent node is always less than or equal to its children, meaning the smallest value is at the root. 
# In a max-heap, the parent node is always greater than or equal to its children, meaning the largest value is at the root.

In [ ]:
# Practice 8
# What data structure would be useful for finding the top 5 pollution values efficiently?
# Write your answer in a comment.
# A min-heap of size 5 would be the most efficient data structure. 
# By keeping only 5 elements in the heap, you can compare new values 
# against the smallest of the "top 5" in O(1) time and update in O(log 5).

In [11]:
# Practice 9
# Create a NumPy array with these temperatures: [70, 72, 75, 80]

# Your code here:
import numpy as np

temps = np.array([70, 72, 75, 80])

In [13]:
# Practice 10
# Add 10 to every value in arr using NumPy (no loop).

# Your code here:
temps = temps + 10

print(temps)

[80 82 85 90]

In [16]:
# Practice 11
# Find the mean and max of arr.

# Your code here:
min_temp=temps.min()
print(min_temp)
max_temp=temps.max()
print(max_temp)

80
90

In [17]:
# Practice 12
# What is broadcasting?
# Write a short answer in a comment.
# Practice 12
# Broadcasting is a NumPy feature that allows operations between arrays of 
# different shapes. It "stretches" the smaller array (like a single number) 
# to match the shape of the larger array so element-wise math can occur.

In [ ]:
# Practice 13
# Why is NumPy often faster than Python loops?
# Write a short answer in a comment.
# Practice 13
# NumPy is faster because it uses "vectorization" and pre-compiled C code. 
# It performs operations on entire blocks of memory at once, avoiding the 
# overhead of Python's type-checking and loop processing.

In [26]:
# Practice 14
# Clean the city column in df so capitalization and spaces are fixed.
# Hint: use .str.strip() and .str.title()

# Your code here:
df["city"].str.strip()
df["city"].str.title()

0        Memphis
1       Memphis
2      Nashville
3        Memphis
4      Knoxville
5      Nashville
6    Chattanooga
7        Memphis
Name: city, dtype: object

In [33]:
# Practice 15
# Filter the rows where pollution > 50.

# Your code here:

high_pollution = df[df["pollution"] > 50]

high_pollution

        city  pollution  year
0    Memphis         55  2020
1   memphis          60  2021
3    Memphis         70  2022
5  Nashville         65  2022
7    Memphis         52  2021

In [37]:
# Practice 16
# Find the average pollution by city.

# Your code here:

df.groupby("city")["pollution"].mean()

city
Chattanooga    45.0
Knoxville      30.0
Memphis        59.0
Nashville      52.5
memphis        60.0
Name: pollution, dtype: float64

In [90]:
# Practice 17
# Count how many records appear in each year.

# Your code here:
df["year"].value_counts()

#print(df14["year"].value_counts().sort_index())

year
2021    3
2022    3
2020    2
Name: count, dtype: int64

In [93]:
# Practice 18
# Create a new column called HighPollution that is 1 when pollution > 50 and 0 otherwise.

# Your code here:

import numpy as np

#df["HighPollution"] = 0

#df.loc[df["pollution"] > 50, "HighPollution"] = 1

#df.head()



df["HighPollution"] = (df["pollution"] > 50).astype(int)

df.head()

        city  pollution  year  HighPollution   z_score  pollution_zscore
0    Memphis         55  2020              1  0.215761          0.215761
1    Memphis         60  2021              1  0.590998          0.590998
2  Nashville         40  2020              0 -0.909949         -0.909949
3    Memphis         70  2022              1  1.341471          1.341471
4  Knoxville         30  2021              0 -1.660422         -1.660422

In [51]:
# Practice 19
# Find all rows where the city contains 'Memphis'.
# Make sure your code still works even if capitalization differs.

# Your code here:
city_mem = df.loc[df["city"].str.contains("Memphis", case=False)]
print(city_mem)

       city  pollution  year  HighPollution
0   Memphis         55  2020              1
1  memphis          60  2021              1
3   Memphis         70  2022              1
7   Memphis         52  2021              1

In [ ]:
# Practice 20
# When would you use Pandas instead of NumPy?
# Write a short answer in a comment.
#Use Pandas when working with CSVs, etc., that have mixed data types (strings, dates, and numbers) and named columns. 
#Pandas is better for data cleaning, merging datasets, and descriptive statistics.

In [ ]:
# Practice 21
# When is NumPy better than Pandas?
# Write a short answer in a comment.
# NumPy is better for heavy mathematical computations, multi-dimensional arrays (tensors), and situations where speed and memory efficiency are critical. 
#It is the "engine" that powers Pandas but is less bloated for pure numerical work.

In [ ]:
# Practice 22
# Why is vectorization important?
# Write a short answer in a comment.
#Vectorization allows you to perform operations on entire arrays at once without explicit Python loops. 
#This is important because it shifts the work to highly optimized C/Fortran code, making execution significantly faster and the code easier to read.

In [56]:
# Practice 23
# Find the top 3 cities by average pollution using Pandas.
# Be careful: clean the city names first.

# Your code here:
df["city"].str.strip()
df["city"].str.title()

city_avg = df.groupby("city")["pollution"].mean()

top_3 = city_avg.sort_values(ascending=False).head(3)

print(top_3)

city
memphis      60.0
Memphis      59.0
Nashville    52.5
Name: pollution, dtype: float64

In [58]:
# Practice 24
# Compute z-scores for the pollution column:
# z = (value - mean) / standard_deviation

# Your code here:
mean_val = df["pollution"].mean()
std_val = df["pollution"].std()

df["z_score"] = (df["pollution"] - mean_val) / std_val

df.head()

        city  pollution  year  HighPollution   z_score
0    Memphis         55  2020              1  0.215761
1   memphis          60  2021              1  0.590998
2  Nashville         40  2020              0 -0.909949
3    Memphis         70  2022              1  1.341471
4  Knoxville         30  2021              0 -1.660422

In [59]:
# Practice 25
# Fix this code so it works correctly:
# df[df['pollution'] > '50']

# Write the corrected code below:

df[df['pollution'] > 50]

        city  pollution  year  HighPollution   z_score
0    Memphis         55  2020              1  0.215761
1   memphis          60  2021              1  0.590998
3    Memphis         70  2022              1  1.341471
5  Nashville         65  2022              1  0.966234
7    Memphis         52  2021              1 -0.009381

In [ ]:
# Practice 26
# Explain why this is slower than vectorized NumPy code:
# for i in range(len(arr)):
#     arr[i] += 1
#
# Write your answer in a comment.
 # Big O(N) vs Big O(1)
#Python loop, which has to "talk" to the Python interpreter for every single element. 
#Vectorized NumPy code operates compiled C code at the memory level, processing the entire array in one step rather than row-by-row.

In [61]:
# Practice 27
# Use groupby to find the year with the highest average pollution.

# Your code here:
yearly_avg = df.groupby("year")["pollution"].mean()
    
yearly_avg.idxmax()

np.int64(2022)

In [74]:
# Practice 28
# Find the city with the highest TOTAL pollution.
# Then print BOTH the city name and the total pollution value.
#
# Hint: use groupby + sum, then find the max.

# Your code here:
city_totals = df.groupby("city")["pollution"].sum()


top_city_name = city_totals.idxmax()

top_city_value = city_totals.max()

print(f"City: {top_city_name}, Total Pollution: {top_city_value}")

City: Memphis, Total Pollution: 177

In [76]:
# Practice 29
# For each city, find the YEAR where that city had its highest pollution.
#
# Output should show:
# city, year, pollution

#For this problem let's make it a little more interesting
# 1. Clean the city column by making sure there is no whitespace errors 
# and make the first letter in city capital and the rest lower.
# 2. Sort appropriately
# 3. Use groupby

# Your code here:
df["city"] = df["city"].str.strip().str.title()


df_sorted = df.sort_values(["city", "pollution"], ascending=False)


highest_years = df_sorted.groupby("city").head(1)


highest_years[["city", "year", "pollution"]]

          city  year  pollution
5    Nashville  2022         65
3      Memphis  2022         70
4    Knoxville  2021         30
6  Chattanooga  2022         45

In [ ]:
# Practice 30
# Explain when a heap would outperform sorting.
# Write a short answer in a comment.

# A heap outperforms sorting when you only need the top few elements and dont need to sort the entire dataset.

In [87]:
# Practice 31
# Clean and deduplicate the city column, then display the unique city names in sorted order.

# Your code here:

df["city"] = df["city"].str.strip().str.title()

unique_cities = df["city"].drop_duplicates().sort_values()

print(unique_cities)

6    Chattanooga
4      Knoxville
0        Memphis
2      Nashville
Name: city, dtype: object

In [77]:
# Practice 32
# Combine NumPy + Pandas:
# Create a new column called pollution_zscore using the z-score formula.

# Your code here:


mean_val = df["pollution"].mean()
std_val = df["pollution"].std()

df["pollution_zscore"] = (df["pollution"] - mean_val) / std_val

df.head()

        city  pollution  year  HighPollution   z_score  pollution_zscore
0    Memphis         55  2020              1  0.215761          0.215761
1    Memphis         60  2021              1  0.590998          0.590998
2  Nashville         40  2020              0 -0.909949         -0.909949
3    Memphis         70  2022              1  1.341471          1.341471
4  Knoxville         30  2021              0 -1.660422         -1.660422

## Harder Programming Problems

In [85]:
# Harder Problem 1
# You are given daily pollution readings for several cities.
# Write code that returns the TOP 2 pollution readings for each city.
#
# Requirements:
# 1. Clean the city names first.
# 2. Group by city.
# 3. For each city, return the two highest pollution values in descending order.
#
# Hint:
# You may use groupby + apply, or sort_values + groupby + head.

# Your code here:

# Harder Problem 1


df["city"] = df["city"].str.strip().str.title()


df_sorted = df.sort_values(["city", "pollution"], ascending= False)


top_2_per_city = df_sorted.groupby("city").head(2)


print(top_2_per_city[["city", "pollution"]])

          city  pollution
5    Nashville         65
2    Nashville         40
3      Memphis         70
1      Memphis         60
4    Knoxville         30
6  Chattanooga         45

In [82]:
# Harder Problem 2
# Build a small analytics report from df after cleaning city names.
#
# Your report should include:
# 1. the city with the highest average pollution
# 2. the year with the highest average pollution
# 3. the number of rows where pollution > 50

# Store your results in clearly named Python variables and print them.

# Your code here:

df["city"] = df["city"].str.strip().str.title()


city_avg = df.groupby("city")["pollution"].mean()
highest_avg_city = city_avg.idxmax()


year_avg = df.groupby("year")["pollution"].mean()
highest_avg_year = year_avg.idxmax()

# 4. The number of rows where pollution > 50
# We filter the dataframe and then check the length of the result
high_pollution_count = len(df[df["pollution"] > 50])

# Print the Analytics Report
print("--- Analytics Report ---")
print(f"City with highest avg pollution: {highest_avg_city}")
print(f"Year with highest avg pollution: {highest_avg_year}")
print(f"Number of high pollution records (>50): {high_pollution_count}")

--- Analytics Report ---
City with highest avg pollution: Memphis
Year with highest avg pollution: 2022
Number of high pollution records (>50): 5

In [83]:
# Harder Problem 3
# We are modeling connections between cities.
# Each city is connected to other cities it shares events with.

# The graph is represented as a dictionary:
graph = {
    "Memphis": ["Nashville", "Jackson"],
    "Nashville": ["Memphis", "Knoxville"],
    "Knoxville": ["Nashville"],
    "Jackson": ["Memphis"]
}

# 1. How many neighbors does Memphis have?
# 2. Write code to print all neighbors of Nashville.
# 3. Write code to check if Memphis is connected to Knoxville.
# 4. Write code to count how many total connections exist in the graph.
#    (Hint: be careful not to double count edges)


memphis_neighbors_count = len(graph["Memphis"])
print(f"1. Memphis has {memphis_neighbors_count} neighbors.")

# 2. Write code to print all neighbors of Nashville.
print("2. Neighbors of Nashville:", graph["Nashville"])

# 3. Write code to check if Memphis is connected to Knoxville.
# We check if "Knoxville" is in the list of Memphis's neighbors.
is_connected = "Knoxville" in graph["Memphis"]
print(f"3. Is Memphis connected to Knoxville? {is_connected}")

# 4. Write code to count how many total connections exist in the graph.
# (Hint: be careful not to double count edges)
total_connections = 0
for city in graph:
    total_connections += len(graph[city])

# Since every connection is listed twice (A->B and B->A), divide by 2
final_count = total_connections // 2
print(f"4. Total unique connections: {final_count}")

1. Memphis has 2 neighbors.
2. Neighbors of Nashville: ['Memphis', 'Knoxville']
3. Is Memphis connected to Knoxville? False
4. Total unique connections: 3

## Runnable Answer Key

Run the single code cell below to see one possible solution set.

In [86]:
# ANSWER KEY: run this cell after working the problems yourself

import numpy as np
import pandas as pd
import heapq

# fresh copies so answers don't depend on previous edits
df_ans = pd.DataFrame({
    "city": ["Memphis", "memphis ", "Nashville", "Memphis", "Knoxville", "Nashville", "Chattanooga", "Memphis"],
    "pollution": [55, 60, 40, 70, 30, 65, 45, 52],
    "year": [2020, 2021, 2020, 2022, 2021, 2022, 2022, 2021]
})
arr_ans = np.array([70, 72, 75, 80])

print("===== SHORT ANSWERS =====")
print("1. Dictionary, because it is good for counting frequencies by key.")
print("2. Searching a list is O(n).")
print("3. Use a set (or drop_duplicates in Pandas) to remove duplicates.")
print("4. Dictionaries use hashing, so average-case lookup is O(1).")
print("5. A list is better when order matters or duplicates should be kept.")
print("6. A heap is used for priority queues and top-k style problems.")
print("7. Min-heap: smallest value on top. Max-heap: largest value on top.")
print("8. A heap is useful for top-k values.")
print("12. Broadcasting means NumPy can apply operations across an array automatically.")
print("13. NumPy is faster because operations are vectorized and implemented efficiently in lower-level code.")
print("20. Use Pandas for labeled/tabular data, grouping, filtering, and cleaning.")
print("21. Use NumPy for raw numerical arrays and fast numerical computation.")
print("22. Vectorization is important because it avoids slow Python loops.")
print("26. Python loops are slower because they operate element-by-element in Python instead of using fast vectorized operations.")
print("30. A heap can outperform sorting when you only need the top k items instead of sorting everything.")

print("\n===== CODE ANSWERS =====")

# 3
cities = ["Memphis", "Nashville", "Memphis", "Knoxville", "Nashville"]
ans3 = list(set(cities))
print("3.", ans3)

# 6
values = [55, 30, 70, 45, 60]
heap = values.copy()
heapq.heapify(heap)
print("6.", heap)

# 9
ans9 = np.array([70, 72, 75, 80])
print("9.", ans9)

# 10
ans10 = arr_ans + 10
print("10.", ans10)

# 11
print("11. mean =", np.mean(arr_ans), "max =", np.max(arr_ans))

# 14
df14 = df_ans.copy()  #I did this so I wouldn't change the code each time:)
df14["city"] = df14["city"].str.strip().str.title()
print("14.")
print(df14)

# 15
print("15.")
print(df14[df14["pollution"] > 50])

# 16
print("16.")
print(df14.groupby("city")["pollution"].mean())

# 17
print("17.")
print(df14["year"].value_counts().sort_index())

# 18
df18 = df14.copy()
df18["HighPollution"] = (df18["pollution"] > 50).astype(int)
print("18.")
print(df18)

# 19
print("19.")
print(df14[df14["city"].str.contains("Memphis", case=False, regex=True)])
#don't worry about memorizing regex for the test

# 23
print("23.")
ans23 = (df14.groupby("city")["pollution"].mean().sort_values(ascending=False).head(3))
print(ans23)

# 24
print("24.")
z_pollution = (df14["pollution"] - df14["pollution"].mean()) / df14["pollution"].std()
print(z_pollution)

# 25
print("25.")
print(df14[df14["pollution"] > 50])

# 27
print("27.")
year_avg = df14.groupby("year")["pollution"].mean()
print("Year with highest average pollution:", year_avg.idxmax())
print(year_avg)

# 28
print("28a.")
city_total = df14.groupby("city")["pollution"].sum()
max_city = city_total.idxmax()
max_value = city_total.max()

print(max_city, max_value)

# 29
print("29.")  #pretend like city is messed up:)  
df14["city"] = df14["city"].str.strip().str.title()

result = (df14.sort_values("pollution", ascending=False).groupby("city").head(1))
print(result[["city", "year", "pollution"]])


# 31
print("31.")
clean_unique_cities = sorted(df14["city"].drop_duplicates().tolist())
print(clean_unique_cities)

# 32
print("32.")
df32 = df14.copy()
df32["pollution_zscore"] = (df32["pollution"] - df32["pollution"].mean()) / df32["pollution"].std()
print(df32)

print("\n===== HARDER PROBLEM 1 =====")
hard1 = df14.sort_values(["city", "pollution"], ascending=[True, False]).groupby("city").head(2)
print(hard1)

print("\n===== HARDER PROBLEM 2 =====")
city_avg = df14.groupby("city")["pollution"].mean()
year_avg = df14.groupby("year")["pollution"].mean()
highest_avg_city = city_avg.idxmax()
highest_avg_city_value = city_avg.max()
highest_avg_year = year_avg.idxmax()
highest_avg_year_value = year_avg.max()
count_gt_50 = (df14["pollution"] > 50).sum()
year_to_avg_dict = year_avg.to_dict()   #here, just using dictionary

print("city with highest average pollution:", highest_avg_city, highest_avg_city_value)
print("year with highest average pollution:", highest_avg_year, highest_avg_year_value)
print("number of rows with pollution > 50:", count_gt_50)
print("year -> average pollution:", year_to_avg_dict)





print("\n===== HARDER PROBLEM 3 =====")
graph = {
    "Memphis": ["Nashville", "Jackson"],
    "Nashville": ["Memphis", "Knoxville"],
    "Knoxville": ["Nashville"],
    "Jackson": ["Memphis"]
}

# 1. Number of neighbors
print(len(graph["Memphis"]))  # 2

# 2. Print neighbors of Nashville
print(graph["Nashville"])

# 3. Check connection
print("Knoxville" in graph["Memphis"])  # False

# 4. Count total connections (undirected graph)
total = 0
for city in graph:
    total += len(graph[city])

print(total // 2)  # divide by 2 to avoid double counting

===== SHORT ANSWERS =====
1. Dictionary, because it is good for counting frequencies by key.
2. Searching a list is O(n).
3. Use a set (or drop_duplicates in Pandas) to remove duplicates.
4. Dictionaries use hashing, so average-case lookup is O(1).
5. A list is better when order matters or duplicates should be kept.
6. A heap is used for priority queues and top-k style problems.
7. Min-heap: smallest value on top. Max-heap: largest value on top.
8. A heap is useful for top-k values.
12. Broadcasting means NumPy can apply operations across an array automatically.
13. NumPy is faster because operations are vectorized and implemented efficiently in lower-level code.
20. Use Pandas for labeled/tabular data, grouping, filtering, and cleaning.
21. Use NumPy for raw numerical arrays and fast numerical computation.
22. Vectorization is important because it avoids slow Python loops.
26. Python loops are slower because they operate element-by-element in Python instead of using fast vectorized operations.
30. A heap can outperform sorting when you only need the top k items instead of sorting everything.

===== CODE ANSWERS =====
3. ['Memphis', 'Knoxville', 'Nashville']
6. [30, 45, 70, 55, 60]
9. [70 72 75 80]
10. [80 82 85 90]
11. mean = 74.25 max = 80
14.
          city  pollution  year
0      Memphis         55  2020
1      Memphis         60  2021
2    Nashville         40  2020
3      Memphis         70  2022
4    Knoxville         30  2021
5    Nashville         65  2022
6  Chattanooga         45  2022
7      Memphis         52  2021
15.
        city  pollution  year
0    Memphis         55  2020
1    Memphis         60  2021
3    Memphis         70  2022
5  Nashville         65  2022
7    Memphis         52  2021
16.
city
Chattanooga    45.00
Knoxville      30.00
Memphis        59.25
Nashville      52.50
Name: pollution, dtype: float64
17.
year
2020    2
2021    3
2022    3
Name: count, dtype: int64
18.
          city  pollution  year  HighPollution
0      Memphis         55  2020              1
1      Memphis         60  2021              1
2    Nashville         40  2020              0
3      Memphis         70  2022              1
4    Knoxville         30  2021              0
5    Nashville         65  2022              1
6  Chattanooga         45  2022              0
7      Memphis         52  2021              1
19.
      city  pollution  year
0  Memphis         55  2020
1  Memphis         60  2021
3  Memphis         70  2022
7  Memphis         52  2021
23.
city
Memphis        59.25
Nashville      52.50
Chattanooga    45.00
Name: pollution, dtype: float64
24.
0    0.215761
1    0.590998
2   -0.909949
3    1.341471
4   -1.660422
5    0.966234
6   -0.534712
7   -0.009381
Name: pollution, dtype: float64
25.
        city  pollution  year
0    Memphis         55  2020
1    Memphis         60  2021
3    Memphis         70  2022
5  Nashville         65  2022
7    Memphis         52  2021
27.
Year with highest average pollution: 2022
year
2020    47.500000
2021    47.333333
2022    60.000000
Name: pollution, dtype: float64
28a.
Memphis 237
29.
          city  year  pollution
3      Memphis  2022         70
5    Nashville  2022         65
6  Chattanooga  2022         45
4    Knoxville  2021         30
31.
['Chattanooga', 'Knoxville', 'Memphis', 'Nashville']
32.
          city  pollution  year  pollution_zscore
0      Memphis         55  2020          0.215761
1      Memphis         60  2021          0.590998
2    Nashville         40  2020         -0.909949
3      Memphis         70  2022          1.341471
4    Knoxville         30  2021         -1.660422
5    Nashville         65  2022          0.966234
6  Chattanooga         45  2022         -0.534712
7      Memphis         52  2021         -0.009381

===== HARDER PROBLEM 1 =====
          city  pollution  year
6  Chattanooga         45  2022
4    Knoxville         30  2021
3      Memphis         70  2022
1      Memphis         60  2021
5    Nashville         65  2022
2    Nashville         40  2020

===== HARDER PROBLEM 2 =====
city with highest average pollution: Memphis 59.25
year with highest average pollution: 2022 60.0
number of rows with pollution > 50: 5
year -> average pollution: {2020: 47.5, 2021: 47.333333333333336, 2022: 60.0}

===== HARDER PROBLEM 3 =====
2
['Memphis', 'Knoxville']
False
3